# Generated by Django 2.1.2 on 2018-10-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
