# Generated by Django 2.1.2 on 2018-10-22 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20181019_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
