# Generated by Django 2.1.2 on 2018-11-01 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_background_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('index.html', 'Home')], default='index.html', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='background',
            name='selection',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.BackgroundSelection'),
            preserve_default=False,
        ),
    ]
