# Generated by Django 2.1.2 on 2018-11-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20181101_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundselection',
            name='page',
            field=models.CharField(choices=[('index.html', 'Home')], default='index.html', max_length=10),
        ),
    ]
