# Generated by Django 2.1.2 on 2018-11-02 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20181101_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backgrounds',
            fields=[
                ('backgroundselection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gallery.BackgroundSelection')),
                ('background_name', models.CharField(max_length=200)),
                ('template_url', models.CharField(max_length=200)),
                ('selected', models.BooleanField(default=False)),
            ],
            bases=('gallery.backgroundselection',),
        ),
        migrations.RemoveField(
            model_name='background',
            name='selection',
        ),
        migrations.AlterField(
            model_name='backgroundselection',
            name='page',
            field=models.CharField(choices=[('gallery/index.html', 'Particles-js')], default=('gallery/index.html', 'Particles-js'), max_length=10),
        ),
        migrations.DeleteModel(
            name='Background',
        ),
    ]
